# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_main.ipynb.

# %% auto 0
__all__ = ['IN_NOTEBOOK']

# %% ../nbs/00_main.ipynb 1
import fire
from . import jarvislabs
IN_NOTEBOOK = False

# %% ../nbs/00_main.ipynb 3
if __name__ == '__main__' and not IN_NOTEBOOK:
    fire.Fire({'jl': jarvislabs.JarvisClient()})
