# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_main.ipynb.

# %% auto 0
__all__ = ['main']

# %% ../nbs/00_main.ipynb 1
import fire
from . import jarvislabs

# %% ../nbs/00_main.ipynb 3
def main():
    fire.Fire({'jl': jarvislabs.JarvisClient()})

# %% ../nbs/00_main.ipynb 4
if __main__ == '__name__':
    main()
