name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: [uses: fastai/workflows/quarto-ghp@master]
    env:
      JARVIS_USER_ID_TEST: ${{ secrets.JARVIS_USER_ID_TEST }}
      JARVIS_TOKEN_TEST: ${{ secrets.JARVIS_TOKEN_TEST }}